# Generated by Django 2.2.12 on 2020-11-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201106_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Encuesta'},
        ),
    ]
